### ISSUE TITLE
PR builds fail

### ISSUE THREAD

**Issue by ojongerius** [volCommunity/vol-django#84]
See https://travis-ci.org/volCommunity/vol-django/jobs/295894845 for an example:

```
$ pipenv run python manage.py collectstatic
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 187, in fetch_command
    app_name = commands[subcommand]
KeyError: 'collectstatic'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 194, in fetch_command
    settings.INSTALLED_APPS
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/conf/__init__.py", line 129, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
The command "pipenv run python manage.py collectstatic" failed and exited with 1 during .
Your build has been stopped.
```

I suspect this is because the SECRET_KEY is not available to forks.

**Comment by ojongerius** [comment]
Fixed in #96
